/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controllers.Controlador;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author yh9pl
 */
public class JDNumerico extends javax.swing.JDialog {

    /**
     * Creates new form JDNumerico
     */
    public JDNumerico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbs = new javax.swing.ButtonGroup();
        txtValor1 = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        txtValor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtValor1.setForeground(new java.awt.Color(153, 153, 153));
        txtValor1.setText("Valor 1");
        txtValor1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValor1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValor1FocusLost(evt);
            }
        });
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor1KeyTyped(evt);
            }
        });
        getContentPane().add(txtValor1);
        txtValor1.setBounds(18, 16, 64, 30);

        txtValor2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtValor2.setForeground(new java.awt.Color(153, 153, 153));
        txtValor2.setText("Valor 2");
        txtValor2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValor2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValor2FocusLost(evt);
            }
        });
        txtValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor2KeyTyped(evt);
            }
        });
        getContentPane().add(txtValor2);
        txtValor2.setBounds(103, 16, 64, 30);

        btnOk.setText("Ok");
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOkMouseEntered(evt);
            }
        });
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(18, 70, 150, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 186, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValor1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValor1FocusGained
        this.txtValor1.setForeground(new Color(0x353535));
        this.txtValor1.setBackground(new Color(0xF9F4E0));
        if(this.txtValor1.getText().equals("Valor 1")) {
            this.txtValor1.setText("");
        }
    }//GEN-LAST:event_txtValor1FocusGained

    private void txtValor1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValor1FocusLost
        if(this.txtValor1.getText().equals("")) {
            this.txtValor1.setForeground(new Color(0x999999));
            this.txtValor1.setBackground(new Color(0xFFFFFF));
            this.txtValor1.setText("Valor 1");
        } else {
            this.txtValor1.setBackground(new Color(0xFBF7E8));
        }
    }//GEN-LAST:event_txtValor1FocusLost

    private void txtValor2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValor2FocusGained
        this.txtValor2.setForeground(new Color(0x353535));
        this.txtValor2.setBackground(new Color(0xF9F4E0));
        if(this.txtValor2.getText().equals("Valor 2")) {
            this.txtValor2.setText("");
        }
    }//GEN-LAST:event_txtValor2FocusGained

    private void txtValor2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValor2FocusLost
        if(this.txtValor2.getText().equals("")) {
            this.txtValor2.setForeground(new Color(0x999999));
            this.txtValor2.setBackground(new Color(0xFFFFFF));
            this.txtValor2.setText("Valor 2");
        } else {
            this.txtValor2.setBackground(new Color(0xFBF7E8));
        }
    }//GEN-LAST:event_txtValor2FocusLost

    private void btnOkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseEntered
        // TODO add your handling code here:
        this.btnOk.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnOkMouseEntered

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        if((this.txtValor1.getText().equals("Valor 1") || this.txtValor1.getText().equals("") || this.txtValor1.getText().equals("0")) ||
           (this.txtValor2.getText().equals("Valor 2") || this.txtValor2.getText().equals("") || this.txtValor2.getText().equals("0"))) {
            JOptionPane.showMessageDialog(this, "Hay campos vacíos.", "Arboles de desición", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(Integer.parseInt(this.txtValor1.getText()) > Integer.parseInt(this.txtValor2.getText())) {
            JOptionPane.showMessageDialog(this, "El primer valor siempre debe ser menor al segundo.", "Arboles de desición", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(Integer.parseInt(this.txtValor1.getText()) == Integer.parseInt(this.txtValor2.getText())) {
            JOptionPane.showMessageDialog(this, "Los dos valores no pueden ser iguales.", "Arboles de desición", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(!Controlador.valoresNumericos.isEmpty())
            Controlador.valoresNumericos.clear();
        Controlador.valoresNumericos.add(this.txtValor1.getText());
        Controlador.valoresNumericos.add(this.txtValor2.getText());
        System.out.println(Controlador.valoresNumericos);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void txtValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            evt.consume();
        }
        if(this.txtValor1.getText().indexOf('0') == 0) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValor1KeyTyped

    private void txtValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor2KeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            evt.consume();
        }
        if(this.txtValor2.getText().indexOf('0') == 0) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValor2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDNumerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDNumerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDNumerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDNumerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDNumerico dialog = new JDNumerico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnOk;
    private javax.swing.JPanel jPanel1;
    public javax.swing.ButtonGroup rdbs;
    public javax.swing.JTextField txtValor1;
    public javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
